spring.application.name=api
spring.config.import=optional:file:.env
#a porta que o sistema está rodando
server.port= 8080

#configuração do banco em dev. Em Produção tenho que usar variaveís de ambiente 
spring.datasource.url=jdbc:mysql://localhost:3306/falamaria_db
spring.datasource.username=root
spring.datasource.password=

api.security.token.secret= ${JWT_SECRETA}  

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
